### PR TITLE
Milestone 6: Friendship v2

### PR DESCRIPTION
**Pull request by Diegodsha**
- Implemented two-rows friendships
- Added the appropriate `rspec` test coverage

### CODE REVIEW

**Review by ElijahTobs — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

## Hi @Diegodsha and @chuckbuckethead  :wave: 

You've done well so far :+1:  and I commend you for that :clap: 
However, there are still some changes to be made before this milestone can be approved.

## REQUIRED

* [x] When user `A` sends a friendship invite to user `B`, user `B` is supposed to have a button to `accept` or `reject` the friendship but your app currently displays the text `Friendship Pending`.



### Make the change and submit or another review
## Happy Coding :computer: 

_Feel free to reach out to me on slack_ **`@Elijah Ayandokun`**
  **Elijah O. Ayandokun**
[Github](https://github.com/ElijahTobs) | [LinkedIn](https://www.linkedin.com/in/ayandokunelijah/) | [Twitter](https://twitter.com/ElijahTobs)

**Comment by Diegodsha** [comment]
Hi, @ElijahTobs we have that feature implemented but we decide to display it in the user profile view as shown in the picture below, we thought that it could bring a closer experience to real social media  (hope that makes sense).

friendaccept

**Comment by crgc** [comment]
Added **Accept** and **Reject** buttons to `users` index page

**Review by NtwaliHeritier — APPROVED** [review]
### **STATUS: APPROVED✔✔✔✔**

Great work making the required changes.

You can merge👏👏👏👏

Happy coding💻💻💻💻

**Pull request merged**
