### PR TITLE
Milestone 1: Prepare data architecture documentation

### PR DESCRIPTION
**Pull request by crgc**
- Added Entity Relationship Diagram (ERD)

### CODE REVIEW

**Review by enaburekhan — CHANGES_REQUESTED** [review]
# Status: Changes required:wrench::hammer::full_moon:
Hi team!
Nice start:clap::clap:. 

**To improve**
Kindly use the content of the ERD in this  [screen-shot](https://imgur.com/a/IrlULPh) to update the project ERD.

Make the above-required changes and when you are ready, request another review.

Do have questions/comments? kindly drop them :point_down: and ping me on slack @ Eric Enaburekhan to respond.
Happy hacking:blush:
Eric Enaburekhan.

**Comment by crgc** [comment]
Small caveat: all of the relations to `User` are actually zero-to-many instead of one-to-many, and our ERD reflects that fact.

**Review by GzimAsani — APPROVED** [review]
# STATUS: Millstone Accepted :green_circle: 

### Hello **TEAM**, thank you for making the required changes, your have met all the requirements for this millstone, great job and good luck with the next ones :muscle: :+1: 

_**PS: Don't forget to submit a project completion form :thought_balloon:**_

# HAPPY CODING :computer: :desktop_computer:

**Review by descholar-ceo — CHANGES_REQUESTED** [review]
# Status: Invalid Submission :x: :disappointed: :stop_sign: 
## Hello @Diegodsha and @chuckbuckethead   :handshake: :handshake: :handshake: 

Thank you for submitting a code review request. And congratulations on that you have completed this milestone. However your code review request is marked as invalid due to the following reasons:

1. It looks like that you submitted a wrong PR, you should have submitted a Milestone: friendships v1. Kindly submit a right PR link.

Happy coding!!!
___
_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

**Pull request merged**
